### ISSUE TITLE
Coroutine Listeners Fail In Latest Builds

### ISSUE THREAD

**Issue by kevinconway** [asyncdef/eventemitter#2]
This test (https://github.com/asyncdef/eventemitter/blob/master/eventemitter/test_emitter.py#L27) is designed to check if coroutines can be used as event handlers. The test is passing under the currently released build of Python 3.5, but is failing under the lasted Python 3.5-development and Python 3.6-nightly builds.

**Comment by Zearin** [comment]
On my own machine, one of the tests was failing (`test_emitter_emits_async_coro`).  

If I changed this line:

```
await asyncio.sleep(0)
```

to this:

```
await asyncio.sleep(0.00001)
```

Then the test passes for me.

---

Maybe the loop sees `0` and performs a no-op for performance…?

Not sure if this is what's failing on Travis-CI.
