### ISSUE TITLE
Allow any callable as event listeners?

### ISSUE THREAD

**Issue by Zearin** [asyncdef/eventemitter#6]
While the normal practice is to use functions (async or not) as event listeners, is there any reason not to allow any `callable` as a listener?  

If you are okay with this, I will update the docstrings accordingly.  (Napoleon-style, of course…_tally-ho!_ :P)

**Comment by kevinconway** [comment]
I believe that is a more accurate description than (def or async def). I would just ask that we keep it clear that it can be any callable including functions that produce coroutine objects.
