### ISSUE TITLE
Document relationship between `iterable` and `emitter`

### ISSUE THREAD

**Issue by Zearin** [asyncdef/eventemitter#7]
Currently, the module docstring of `iterable` says that its 2 classes wrap the `EventEmitter` class.  

However, this isn’t really true; the classes in `iterable` aren’t used anywhere in `emitter`.
- If this is intentional, the relationship between both modules should be better explained.
- If this is unintentional (i.e. waiting to be implemented), please let me know if there is any way I can help.

**Comment by kevinconway** [comment]
`EventIterable` consumes an `EventEmitter` and an event name as arguments to the `__init__` method. The purpose is to convert an emitter into something you can loop over. It's a pattern I've used before in JS that I found easier to manage than using the emitter callback API directly. Maybe calling it an adapter is a better way of describing the relationship than wrapping?

I don't expect any of the actual code from the emitter module to make its way into iterable. The iterable module is designed to consume any valid implementation of an emitter.

**Comment by Zearin** [comment]
Ah!  Okay.  Now I understand.  What the documentation needs is this (rough paraphrasing):
- “Here’s how you use an `EventEmitter` the “normal” way. It mimics Node.js-style EventEmitters.” «provide example» 
- “Here’s an alternative way you can use an `EventEmitter`.  This `iterator` module provides concrete implementations of `collections.abc.AsyncIterable` and `collections.abc.AsyncIterator`.  They allow you to loop over an emitter object, like so:” «provide example»

Could you write the second example?  (It would also help if it showcased a situation where it’s clearly preferable to the normal emitter API.)

**Comment by Zearin** [comment]
> `EventIterable` consumes an `EventEmitter` and an event name as arguments to the `__init__` method. The purpose is to convert an emitter into something you can loop over.

Also, if I’m reading the code correctly—is it possible to create an emitter, pass it to `EventIterable` for some looping, and _afterwards_ continue to use the emitter?  

That would be pretty cool.

**Comment by Zearin** [comment]
> and afterwards continue to use the emitter?

(Forgot to add to this: “…using its normal API?”)

**Comment by kevinconway** [comment]
I agree whole-heartedly that this feature needs some better documentation and example use cases. I'll look at some of my old JS work and see what the Python adaptations would look like.

Also, you are correct that the emitter is still available for use after creating an iterable from it. The iterable is able to bind to the emitter as a listener which leaves the emitter in a perfectly usable state. If can also be used to feed multiple iterables.

**Comment by Zearin** [comment]
> I agree whole-heartedly that this feature needs some better documentation and example use cases. I'll look at some of my old JS work and see what the Python adaptations would look like.

Great! :)

> Also, you are correct that the emitter is still available for use after creating an iterable from it. The iterable is able to bind to the emitter as a listener which leaves the emitter in a perfectly usable state. If can also be used to feed multiple iterables.

Oh, that is awesome.  That basically means that the dev doesn’t need to make a choice between A _or_ B; they can start with A, and add as much (or as little) of B as they like.  

That is opt-in flexibility.  I think it makes the package more attractive.  Nice. :)
