### ISSUE TITLE
Explicitly mention semantic-versioning support/non-support 

### ISSUE THREAD

**Issue by Zearin** [asyncdef/eventemitter#8]
I personally love [semantic versioning](http://semver.org).  I think it would be good to follow it in this project.  
- If you agree: awesome!  I’ll add a short mention that the project follows semantic versioning.
- If you disagree: that’s okay, too!  However, I think it’s still a good idea to explicitly mention that the project _doesn't_ follow it. 

What do you think?

**Comment by kevinconway** [comment]
:+1: for semver. That's how I'm currently managing the version numbers for this lib. I've been intentionally keeping it under v1.0.0 so we aren't bound yet by backwards compat.

Certainly, there is a spec we're following for EventEmitter. The additional tools, like EventIterable, don't have a node standard lib equivalent and I wanted us to have some room for creativity before locking down an api contact.

**Comment by Zearin** [comment]
> :+1: for semver. That's how I'm currently managing the version numbers for this lib. I've been intentionally keeping it under v1.0.0 so we aren't bound yet by backwards compat.
> 
> Certainly, there is a spec we're following for EventEmitter. The additional tools, like EventIterable, don't have a node standard lib equivalent and I wanted us to have some room for creativity before locking down an api contact.

Awesome!  I agree with all of that.  

Let the creativity flow. :)
