### ISSUE TITLE
Add a decorator-style listener binding

### ISSUE THREAD

**Issue by notpushkin** [asyncdef/eventemitter#9]
Something like:

```py
emitter = EventEmitter()

@emitter.on('an_event')
def event_handler(event, *args, **kwargs):
    print((event, *args, **kwargs))
```

This can be achieved by making the `listener` argument in `add_listener` optional, and returning a decorator if it's omitted. Something like this:

```py
def add_listener(self, event, listener=None, _decorated=False):
    if listener is None:
        return functools.partial(self.add_listener, event, _decorated=True)

    self.emit('new_listener', event, listener)
    self._listeners[event].append(listener)
    self._check_limit(event)
    return listener if _decorated else self
```

**Comment by kevinconway** [comment]
I like the idea as think it would be a valuable addition to the library. Rather than modify the event emitter object itself, would it also meet your goal if we provided a wrapper like the iterator? For example, 

``` python
emitter = Decorator(EventEmitter())

@emitter.on('event')
def handler(event, *args, **kwargs):
    print(event, args, kwargs)
```

I'd like to keep the raw emitter implementation as simple as possible and add all new functionality add a wrapper where possible.

**Comment by notpushkin** [comment]
Maybe a subclass rather than a wrapper? It's mostly [used as a mixin](https://github.com/asyncdef/eventemitter/blob/148b700c5846d8fdafc562d4326587da5447223f/eventemitter/emitter.py#L41), I guess, but there would be no way to subclass a wrapper (without invloving some tricky black magic and metaclasses).

It still seems more "pythonic" to me to use a decorator, though. Maybe you can rename the raw class to something like `BaseEventEmitter`, subclass it and add things there (maybe with mixins or so)? (That's [what I do](https://github.com/Songbee/webtorrent-remote-python/blob/3dc61985c931f30d8a0f27d1c20f1367305b389a/webtorrent/client.py) sometimes, actually).

**Comment by kevinconway** [comment]
There are a couple of reasons why I prefer the decorator approach. One reason is that it keeps the `EventEmitter` interface consistent with the [Node.js](https://nodejs.org/api/events.html) interface that it is based on. Another reason is that it allows the two features to be subclassed or extended separately. The `Decorator` class would accept any valid implementation of `EventEmitter` which means any and all `EventEmitter` subclasses could be passed in. For example:

``` python

class User(EventEmitter):

    def __init__(self):
        super().__init__()
        self._name = None

    @property
    def name(self):
        return self._name

    @name.setter
     def set_name(self, value):
        self._name = value
        self.emit('name_changed', value)

user = User()
on = Decorator(user)

@on('name_changed')
def log_event(event, name):
    print(event, name)

user.name = 'Maria'
```

I believe keeping the decorator single-purpose and only having it expose a special version of `on` would resolve your concerns around making subclassing more difficult. All the same subclassing rules and features exist for `EventEmitter` and any valid implementation can be adapted to a decorator as needed.
